from scripts.network import Network


class G_UNetResidual_Ext2(Network):

    def getOutput(self):
        return self.layers['conv9_gl']

    def setup(self, is_training, num_classes):

        (self.feed('data')
                .g_conv('Z2', 'C4', 7, 32, 1, 1, padding='SAME', name='conv1_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv1_bn1')
                #.dropout(keep_prob=0.9, is_training=is_training, name='conv1_dr1')
                .relu(name='conv1_rl1')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv1_mp1'))

        (self.feed('conv1_rl1')
                .g_residual_block(use_dropout=False, name='conv1_add_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual4', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual5', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual6', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual7', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv1_add_residual8', padding='SAME')
                )

        (self.feed('conv1_mp1')
                .g_conv('C4', 'C4', 3, 64, 1, 1, padding='SAME', name='conv2_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv2_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv2_dr1')
                .relu(name='conv2_rl1')
                .g_residual_block(use_dropout=False, name='conv2_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_residual3', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv2_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv2_dr2')
                .relu(name='conv2_rl2')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv2_mp1'))

        (self.feed('conv2_rl2')
                .g_residual_block(use_dropout=False, name='conv2_add_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_add_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_add_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_add_residual4', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_add_residual5', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_add_residual6', padding='SAME')
                )

        (self.feed('conv2_mp1')
                .g_conv('C4', 'C4', 3, 128, 1, 1, padding='SAME', name='conv3_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv3_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv3_dr1')
                .relu(name='conv3_rl1')
                .g_residual_block(use_dropout=False, name='conv3_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_residual4', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv3_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv3_dr2')
                .relu(name='conv3_rl2')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv3_mp1'))

        (self.feed('conv3_rl2')
                .g_residual_block(use_dropout=False, name='conv3_add_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_add_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_add_residual3', padding='SAME')
                )

        (self.feed('conv3_mp1')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv4_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv4_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv4_dr1')
                .relu(name='conv4_rl1')
                .g_residual_block(use_dropout=False, name='conv4_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual4', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual5', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual6', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv4_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv4_dr2')
                .relu(name='conv4_rl2')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv4_mp1'))

        (self.feed('conv4_mp1')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv5_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv5_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv5_dr1')
                .relu(name='conv5_rl1')
                .g_residual_block(use_dropout=False, name='conv5_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv5_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv5_residual3', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv5_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv5_dr2')
                .relu(name='conv5_rl2')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv5_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv5_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv5_dr3')
                .relu(name='conv5_rl3')
                .upsampling(name='conv5_up'))

        (self.feed('conv5_up', 'conv4_rl2')
                .g_concat(name='conv6_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn0')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv6_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv6_dr1')
                .relu(name='conv6_rl1')
                .g_residual_block(use_dropout=False, name='conv6_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual4', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual5', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual6', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv6_dr2')
                .relu(name='conv6_rl2')
                .g_conv('C4', 'C4', 3, 128, 1, 1, padding='SAME', name='conv6_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv6_dr3')
                .relu(name='conv6_rl3')
                .upsampling(name='conv6_up'))

        (self.feed('conv6_up', 'conv3_add_residual3')
                .g_concat(name='conv7_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn0')
                .g_conv('C4', 'C4', 3, 128, 1, 1, padding='SAME', name='conv7_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv7_dr1')
                .relu(name='conv7_rl1')
                .g_residual_block(use_dropout=False, name='conv7_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv7_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv7_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv7_residual4', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv7_dr2')
                .relu(name='conv7_rl2')
                .g_conv('C4', 'C4', 3, 64, 1, 1, padding='SAME', name='conv7_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv7_dr3')
                .relu(name='conv7_rl3')
                .upsampling(name='conv7_up'))

        (self.feed('conv7_up', 'conv2_add_residual6')
                .g_concat(name='conv8_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn0')
                .g_conv('C4', 'C4', 3, 64, 1, 1, padding='SAME', name='conv8_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv8_dr1')
                .relu(name='conv8_rl1')
                .g_residual_block(use_dropout=False, name='conv8_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv8_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv8_residual3', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv8_dr2')
                .relu(name='conv8_rl2')
                .g_conv('C4', 'C4', 3, 32, 1, 1, padding='SAME', name='conv8_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv8_dr3')
                .relu(name='conv8_rl3')
                .upsampling(name='conv8_up'))

        (self.feed('conv8_up', 'conv1_add_residual8')
                .g_concat(name='conv9_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv9_bn0')
                .g_conv('C4', 'C4', 3, 32, 1, 1, padding='SAME', name='conv9_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv9_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv9_dr1')
                .relu(name='conv9_rl1')
                .g_conv('C4', 'C4', 3, 3, 1, 1, padding='SAME', name='conv9_2')
                .g_avg_global_pool(name='conv9_gl'))



class G_UNetResidual(Network):

    def getOutput(self):
        return self.layers['conv9_gl']

    def setup(self, is_training, num_classes):

        (self.feed('data')
                .g_conv('Z2', 'C4', 7, 32, 1, 1, padding='SAME', name='conv1_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv1_bn1')
                #.dropout(keep_prob=0.9, is_training=is_training, name='conv1_dr1')
                .relu(name='conv1_rl1')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv1_mp1'))

        (self.feed('conv1_mp1')
                .g_conv('C4', 'C4', 3, 64, 1, 1, padding='SAME', name='conv2_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv2_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv2_dr1')
                .relu(name='conv2_rl1')
                .g_residual_block(use_dropout=False, name='conv2_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv2_residual3', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv2_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv2_dr2')
                .relu(name='conv2_rl2')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv2_mp1'))

        (self.feed('conv2_mp1')
                .g_conv('C4', 'C4', 3, 128, 1, 1, padding='SAME', name='conv3_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv3_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv3_dr1')
                .relu(name='conv3_rl1')
                .g_residual_block(use_dropout=False, name='conv3_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv3_residual4', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv3_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv3_dr2')
                .relu(name='conv3_rl2')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv3_mp1'))

        (self.feed('conv3_mp1')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv4_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv4_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv4_dr1')
                .relu(name='conv4_rl1')
                .g_residual_block(use_dropout=False, name='conv4_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual4', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual5', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv4_residual6', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv4_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv4_dr2')
                .relu(name='conv4_rl2')
                .max_pool(2, 2, 2, 2, padding='VALID', name='conv4_mp1'))

        (self.feed('conv4_mp1')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv5_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv5_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv5_dr1')
                .relu(name='conv5_rl1')
                .g_residual_block(use_dropout=False, name='conv5_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv5_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv5_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv5_residual4')
                .g_batch_norm_tensorflow(input_type='C4', name='conv5_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv5_dr2')
                .relu(name='conv5_rl2')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv5_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv5_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv5_dr3')
                .relu(name='conv5_rl3')
                .upsampling(name='conv5_up'))

        (self.feed('conv5_up', 'conv4_rl2')
                .g_concat(name='conv6_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn0')
                .g_conv('C4', 'C4', 3, 256, 1, 1, padding='SAME', name='conv6_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv6_dr1')
                .relu(name='conv6_rl1')
                .g_residual_block(use_dropout=False, name='conv6_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual4', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual5', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv6_residual6', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv6_dr2')
                .relu(name='conv6_rl2')
                .g_conv('C4', 'C4', 3, 128, 1, 1, padding='SAME', name='conv6_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv6_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv6_dr3')
                .relu(name='conv6_rl3')
                .upsampling(name='conv6_up'))

        (self.feed('conv6_up', 'conv3_rl2')
                .g_concat(name='conv7_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn0')
                .g_conv('C4', 'C4', 3, 128, 1, 1, padding='SAME', name='conv7_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv7_dr1')
                .relu(name='conv7_rl1')
                .g_residual_block(use_dropout=False, name='conv7_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv7_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv7_residual3', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv7_residual4', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv7_dr2')
                .relu(name='conv7_rl2')
                .g_conv('C4', 'C4', 3, 64, 1, 1, padding='SAME', name='conv7_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv7_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv7_dr3')
                .relu(name='conv7_rl3')
                .upsampling(name='conv7_up'))

        (self.feed('conv7_up', 'conv2_rl2')
                .g_concat(name='conv8_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn0')
                .g_conv('C4', 'C4', 3, 64, 1, 1, padding='SAME', name='conv8_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv8_dr1')
                .relu(name='conv8_rl1')
                .g_residual_block(use_dropout=False, name='conv8_residual1', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv8_residual2', padding='SAME')
                .g_residual_block(use_dropout=False, name='conv8_residual3', padding='SAME')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn2')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv8_dr2')
                .relu(name='conv8_rl2')
                .g_conv('C4', 'C4', 3, 32, 1, 1, padding='SAME', name='conv8_2')
                .g_batch_norm_tensorflow(input_type='C4', name='conv8_bn3')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv8_dr3')
                .relu(name='conv8_rl3')
                .upsampling(name='conv8_up'))

        (self.feed('conv8_up', 'conv1_rl1')
                .g_concat(name='conv9_i')
                .g_batch_norm_tensorflow(input_type='C4', name='conv9_bn0')
                .g_conv('C4', 'C4', 3, 32, 1, 1, padding='SAME', name='conv9_1')
                .g_batch_norm_tensorflow(input_type='C4', name='conv9_bn1')
                #.dropout(keep_prob=0.8, is_training=is_training, name='conv9_dr1')
                .relu(name='conv9_rl1')
                .g_conv('C4', 'C4', 3, 3, 1, 1, padding='SAME', name='conv9_2')
                .g_avg_global_pool(name='conv9_gl'))



